#!/bin/bash

echo "Input python version (ex. 3.10)"
read version

sudo apt install software-properties-common -y 
sudo add-apt-repository ppa:deadsnakes/ppa 
sudo apt update
sudo apt install mc
sudo apt install python$version
sudo apt install python3-pip
sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
sudo apt install -y python3-venv